# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - ./**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ""
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
